---
meta:
  name:     (( param "Please name your pipeline" ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  url:      (( param "Please specify the full url of the target Concourse CI" ))
  pipeline: (( grab meta.name ))

  image:    starkandwayne/concourse

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch:       master
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
    access_token: (( param "Please generate a Personal Access Token to be used for creating github releases (do you have a ci-bot?)" ))

groups:
  - name: (( grab meta.pipeline ))
    jobs:
      - test-master
      - test-pr

jobs:
  - name: test-master
    public: true
    plan:
      - { get: git, trigger: true }
      - task: run-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: (( grab meta.image ))
          inputs:
            - { name: git }
          run:
            path: ./git/test.sh
            args: []

  - name: test-pr
    public: true
    plan:
      - { get: git }
      - { get: git-pull-requests, trigger: true, version: every }
      - task: test-pr
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: (( grab meta.image ))
          inputs:
            - { name: git }
            - { name: git-pull-requests }
          run:
            path: ./git-pull-requests/test.sh
            args: []
        on_success:
          put: git-pull-requests
          params:
            path: git-pull-requests
            status: success
        on_failure:
          put: git-pull-requests
          params:
            path: git-pull-requests
            status: failure

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: git
    type: git
    source:
      uri:         (( grab meta.github.uri ))
      branch:      (( grab meta.github.branch ))
      private_key: (( grab meta.github.private_key ))

  - name: git-pull-requests
    type: pull-request
    source:
      access_token: (( grab meta.github.access_token ))
      private_key:  (( grab meta.github.private_key ))
      repo:         (( concat meta.github.owner "/" meta.github.repo ))
      base:         (( grab meta.github.branch ))
