---
meta:
  name:    concourse-pullrequest-playtime
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 0.1.0

  github:
    owner:  starkandwayne
    repo:   concourse-pullrequest-playtime
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))
